"use client";

import { ChangeEvent, PointerEvent, useEffect, useState } from "react";
import { AlignCenter, BookOpen, CalendarDays, Eye, EyeOff, Gamepad2, ImagePlus, MapPin, Maximize2, Save, Settings, Trash2, Tv, WandSparkles } from "lucide-react";
import { featured, media } from "@/lib/data";
import { MediaCard, Poster } from "@/components/media-card";
import { Eyebrow, Stars } from "@/components/ui";

type WallItem = { id:string; src:string; x:number; y:number; width:number; rotate:number };
type Theme = "terminal"|"vhs"|"dream"|"mono"|"cyberpunk"|"barcelona"|"real-madrid"|"chelsea"|"tarantino"|"matrix";
type AvatarShape = "square"|"round";
type SavedProfile = { avatar:string; background:string; banner:string; wall:WallItem[]; hidden:string[]; theme:Theme; avatarShape:AvatarShape };
const modules = [{id:"pantheon",label:"MEU PANTEÃO"},{id:"dna",label:"CULTURAL DNA"},{id:"now",label:"CONSUMINDO AGORA"},{id:"gallery",label:"MINHA PAREDE"},{id:"guest",label:"GUESTBOOK.TXT"}];

const readFile = (file: File) => new Promise<string>((resolve, reject) => {
  const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file);
});

export default function Profile(){
 const [edit,setEdit]=useState(false); const [avatar,setAvatar]=useState(""); const [background,setBackground]=useState(""); const [banner,setBanner]=useState(""); const [wall,setWall]=useState<WallItem[]>([]); const [hidden,setHidden]=useState<string[]>([]); const [theme,setTheme]=useState<Theme>("terminal"); const [avatarShape,setAvatarShape]=useState<AvatarShape>("square"); const [ready,setReady]=useState(false);
 useEffect(()=>{try{const saved=localStorage.getItem("midialog-profile");if(saved){const data=JSON.parse(saved) as SavedProfile & {gallery?:string[]};setAvatar(data.avatar||"");setBackground(data.background||"");setBanner(data.banner||"");setWall(data.wall||data.gallery?.map((src,i)=>({id:`old-${i}`,src,x:5+(i%3)*31,y:5+Math.floor(i/3)*30,width:28,rotate:0}))||[]);setHidden(data.hidden||[]);setTheme(data.theme||"terminal");setAvatarShape(data.avatarShape||"square")}}finally{setReady(true)}},[]);
 const save=()=>{try{localStorage.setItem("midialog-profile",JSON.stringify({avatar,background,banner,wall,hidden,theme,avatarShape}));setEdit(false)}catch{alert("As imagens são grandes demais para o armazenamento do navegador. Tente arquivos menores.")}};
 const addWall=(src:string)=>setWall(old=>[...old,{id:`wall-${Date.now()}-${old.length}`,src,x:4+(old.length%3)*31,y:3,width:28,rotate:0}].slice(0,10));
 const pick=async(e:ChangeEvent<HTMLInputElement>,kind:"avatar"|"background"|"banner"|"wall")=>{const files=Array.from(e.target.files||[]);if(!files.length)return;if(kind==="wall"){const images=await Promise.all(files.slice(0,5).map(readFile));images.forEach(addWall)}else{const image=await readFile(files[0]);if(kind==="avatar")setAvatar(image);else if(kind==="banner")setBanner(image);else setBackground(image)}e.target.value=""};
 const move=(event:PointerEvent<HTMLDivElement>,item:WallItem)=>{if(!edit)return;event.currentTarget.setPointerCapture(event.pointerId);const startX=event.clientX,startY=event.clientY,start={x:item.x,y:item.y};const box=event.currentTarget.parentElement!.getBoundingClientRect();const target=event.currentTarget;target.onpointermove=e=>setWall(all=>all.map(x=>x.id===item.id?{...x,x:Math.max(0,Math.min(100-x.width,start.x+(e.clientX-startX)/box.width*100)),y:Math.max(0,Math.min(92,start.y+(e.clientY-startY)/box.height*100))}:x));target.onpointerup=()=>{target.onpointermove=null;target.onpointerup=null}};
 const updateWall=(id:string,patch:Partial<WallItem>)=>setWall(x=>x.map(i=>i.id===id?{...i,...patch}:i));
 const clearSimilarPixels=(pixels:Uint8ClampedArray,width:number,height:number)=>{const corners=[[0,0],[width-1,0],[0,height-1],[width-1,height-1]];const bg=corners.reduce((sum,[x,y])=>{const n=(y*width+x)*4;return [sum[0]+pixels[n],sum[1]+pixels[n+1],sum[2]+pixels[n+2]]},[0,0,0]).map(v=>v/4);for(let i=0;i<pixels.length;i+=4){const distance=Math.sqrt((pixels[i]-bg[0])**2+(pixels[i+1]-bg[1])**2+(pixels[i+2]-bg[2])**2);if(distance<48)pixels[i+3]=0;else if(distance<85)pixels[i+3]=Math.round(pixels[i+3]*(distance-48)/37)}};
 const removeGifBackground=async(item:WallItem)=>{try{const [{parseGIF,decompressFrames},{GIFEncoder,quantize,applyPalette}]=await Promise.all([import("gifuct-js"),import("gifenc")]);const source=await (await fetch(item.src)).arrayBuffer();const parsed=parseGIF(source);const frames=decompressFrames(parsed,true);const width=parsed.lsd.width,height=parsed.lsd.height;const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d",{willReadFrequently:true});if(!ctx)return;const gif=GIFEncoder();let previous:ImageData|null=null;for(const frame of frames){if(frame.disposalType===3)previous=ctx.getImageData(0,0,width,height);const patch=new ImageData(new Uint8ClampedArray(Array.from(frame.patch)),frame.dims.width,frame.dims.height);ctx.putImageData(patch,frame.dims.left,frame.dims.top);const full=ctx.getImageData(0,0,width,height);const cleaned=new Uint8ClampedArray(full.data);clearSimilarPixels(cleaned,width,height);const palette=quantize(cleaned,256,{format:"rgba4444",oneBitAlpha:true,clearAlpha:true});const index=applyPalette(cleaned,palette,"rgba4444");let transparentIndex=palette.findIndex((color:number[])=>color[3]===0);if(transparentIndex<0)transparentIndex=0;gif.writeFrame(index,width,height,{palette,transparent:true,transparentIndex,delay:Math.max(20,frame.delay||100),repeat:0,dispose:2});if(frame.disposalType===2)ctx.clearRect(frame.dims.left,frame.dims.top,frame.dims.width,frame.dims.height);else if(frame.disposalType===3&&previous)ctx.putImageData(previous,0,0)}gif.finish();const blob=new Blob([gif.bytes()],{type:"image/gif"});const result=await readFile(new File([blob],"transparent.gif",{type:"image/gif"}));updateWall(item.id,{src:result})}catch(error){console.error(error);alert("Não foi possível processar este GIF. Tente um arquivo menor ou com fundo mais uniforme.")}};
 const removeImageBackground=(item:WallItem)=>{if(item.src.startsWith("data:image/gif")){void removeGifBackground(item);return}const image=new Image();image.onload=()=>{const canvas=document.createElement("canvas");const max=900;const scale=Math.min(1,max/Math.max(image.width,image.height));canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);const ctx=canvas.getContext("2d");if(!ctx)return;ctx.drawImage(image,0,0,canvas.width,canvas.height);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);clearSimilarPixels(pixels.data,canvas.width,canvas.height);ctx.putImageData(pixels,0,0);updateWall(item.id,{src:canvas.toDataURL("image/png")})};image.src=item.src};
 const toggle=(id:string)=>setHidden(x=>x.includes(id)?x.filter(y=>y!==id):[...x,id]); const on=(id:string)=>!hidden.includes(id);
 const preset=background.startsWith("preset:")?background.slice(7):"";
 return <div className={`profile-page theme-${theme} ${background&&!preset?"has-custom-background":""} ${preset?`animated-bg bg-${preset}`:""}`} style={background&&!preset?{"--profile-bg":`url("${background}")`} as React.CSSProperties:undefined}>
  <section className={`profile-banner ${banner?"custom-banner":""}`} style={banner?{backgroundImage:`linear-gradient(90deg,rgba(5,7,8,.25),rgba(5,7,8,.7)),url("${banner}")`}:undefined}><div className="banner-code">ESPAÇO://LUCAS/ARQUIVO<br/>SINAL 098.7 FM</div><div className="profile-controls"><button className="button ghost" onClick={()=>edit?save():setEdit(true)}>{edit?<Save size={15}/>:<Settings size={15}/>} {edit?"SALVAR PERFIL":"PERSONALIZAR PERFIL"}</button></div></section>
  <div className="profile-shell"><aside className="profile-side"><div className={`profile-avatar avatar-${avatarShape}`}>{avatar?<img src={avatar} alt="Foto de perfil de Lucas"/>:<span>L</span>}<i>ONLINE</i>{edit&&<div className="avatar-shape"><button className={avatarShape==="square"?"active":""} onClick={()=>setAvatarShape("square")}>QUADRADA</button><button className={avatarShape==="round"?"active":""} onClick={()=>setAvatarShape("round")}>REDONDA</button></div>}</div><h1>Lucas <small>@lucas</small></h1><p>jogos, cinema e coisas nas quais não consigo parar de pensar.</p><div className="profile-loc"><span><MapPin size={12}/> São Paulo, BR</span><span><CalendarDays size={12}/> membro desde 2024</span></div><div className="follow"><b>1,284<small>SEGUIDORES</small></b><b>356<small>SEGUINDO</small></b></div><button className="button primary">＋ SEGUIR</button><div className="status-box"><Eyebrow>MENSAGEM DE STATUS</Eyebrow><p>“na névoa de novo”</p></div><div className="badges"><span>🎬</span><span>🎮</span><span>📚</span><span>🌙</span><span>🕹️</span></div><div className="visits">VISITAS AO PERFIL <b>008421</b><small>VISTO POR ÚLTIMO: HÁ 2 MIN</small></div></aside>
  <div className="profile-main">{edit&&<section className="customizer visual-editor"><div className="editor-heading"><Eyebrow>MODO DE EDIÇÃO / PERSONALIZE TUDO</Eyebrow><p>Envie imagens ou GIFs, escolha um tema e arraste livremente os itens da parede.</p></div><div className="theme-picker">{(["terminal","vhs","dream","mono","cyberpunk","barcelona","real-madrid","chelsea","tarantino","matrix"] as Theme[]).map(t=><button className={theme===t?"selected":""} onClick={()=>setTheme(t)} key={t}><i className={`theme-dot ${t}`}/>{t.replace("-"," ").toUpperCase()}</button>)}</div><div className="upload-controls"><label><ImagePlus size={15}/> FOTO DO PERFIL<input type="file" accept="image/*,.gif" onChange={e=>pick(e,"avatar")}/></label><label><ImagePlus size={15}/> BANNER<input type="file" accept="image/*,.gif" onChange={e=>pick(e,"banner")}/></label><label><ImagePlus size={15}/> FUNDO DA PÁGINA<input type="file" accept="image/*,.gif" onChange={e=>pick(e,"background")}/></label><label><ImagePlus size={15}/> FOTO OU GIF FLUTUANTE<input multiple type="file" accept="image/*,.gif" onChange={e=>pick(e,"wall")}/></label>{(avatar||background||banner||wall.length>0)&&<button className="danger" onClick={()=>{setAvatar("");setBackground("");setBanner("");setWall([])}}><Trash2 size={14}/> LIMPAR IMAGENS</button>}</div><div className="preset-row"><span>FUNDOS ANIMADOS PARA TESTAR:</span>{["signal","aurora","grid"].map(p=><button key={p} onClick={()=>setBackground(`preset:${p}`)} className={`preset ${p}`}>{p==="signal"?"SINAL":p==="grid"?"GRADE":"AURORA"}</button>)}</div><div className="module-toggles">{modules.map(m=><button key={m.id} onClick={()=>toggle(m.id)}>{on(m.id)?<Eye size={14}/>:<EyeOff size={14}/>} {m.label}</button>)}</div></section>}
  {on("gallery")&&wall.length>0&&<section className="profile-module full wall-module wall-only"><div className={`free-wall ${edit?"editing":""}`}>{wall.map((item,i)=><div className="wall-item" onPointerDown={e=>move(e,item)} key={item.id} style={{left:`${item.x}%`,top:`${item.y}%`,width:`${Math.min(item.width,68)}%`,transform:`rotate(${item.rotate}deg)`,zIndex:i+1}}><img draggable={false} src={item.src} alt={`Imagem personalizada ${i+1}`}/>{edit&&<div className="wall-tools"><button title="Centralizar" onPointerDown={e=>e.stopPropagation()} onClick={()=>updateWall(item.id,{x:(100-Math.min(item.width,68))/2,y:3,rotate:0})}><AlignCenter size={12}/></button><button title="Retirar fundo" onPointerDown={e=>e.stopPropagation()} onClick={()=>removeImageBackground(item)}><WandSparkles size={12}/></button><button title="Aumentar" onPointerDown={e=>e.stopPropagation()} onClick={()=>updateWall(item.id,{width:Math.min(68,item.width+5)})}><Maximize2 size={12}/>＋</button><button title="Diminuir" onPointerDown={e=>e.stopPropagation()} onClick={()=>updateWall(item.id,{width:Math.max(12,item.width-5)})}>－</button><button title="Girar" onPointerDown={e=>e.stopPropagation()} onClick={()=>updateWall(item.id,{rotate:item.rotate+5})}>↻</button><button title="Remover" onPointerDown={e=>e.stopPropagation()} onClick={()=>setWall(x=>x.filter(v=>v.id!==item.id))}><Trash2 size={12}/></button></div>}</div>)}</div></section>}
  {on("pantheon")&&<section className="profile-module full"><div className="module-head"><Eyebrow>PINNED SHOWCASE / 01</Eyebrow><h2>MEU PANTEÃO</h2><span>THE THINGS THAT MADE ME</span></div><div className="media-grid profile-faves">{featured.slice(0,4).map(x=><MediaCard item={x} key={x.id}/>)}</div></section>}
  <div className="module-grid">{on("dna")&&<section className="profile-module"><div className="module-head"><Eyebrow>ANALYZED SIGNAL</Eyebrow><h2>CULTURAL DNA</h2><span>UPDATED TODAY</span></div><div className="dna">{[["CINEMA",40],["GAMES",30],["BOOKS",17],["TV",13]].map(([x,n])=><div key={x}><span>{x}</span><i><b style={{width:`${n}%`}}/></i><em>{n}%</em></div>)}</div><div className="dna-tags"><span>HORROR</span><span>SURREALISM</span><span>RPG</span><span>SCI-FI</span><span>PHILOSOPHY</span></div></section>}
  {on("now")&&<section className="profile-module"><div className="module-head"><Eyebrow>LIVE STATUS</Eyebrow><h2>NOW / LATELY</h2><span>3 SIGNALS</span></div><div className="now-list">{[[Gamepad2,"PLAYING",media[1],"12H 48M"],[Tv,"WATCHING",media[2],"S02 E04"],[BookOpen,"READING",media[3],"PAGE 247"]].map(([Icon,label,item,status])=>{const I=Icon as typeof Gamepad2;const m=item as typeof media[0];return <div key={label as string}><I size={17}/><Poster item={m}/><p><small>{label as string}</small><b>{m.title}</b><span>{status as string}</span></p></div>})}</div></section>}</div>
  <div className="module-grid">{on("guest")&&<section className="profile-module"><div className="module-head"><Eyebrow>OLD WEB ENERGY</Eyebrow><h2>GUESTBOOK.TXT</h2><span>42 ENTRIES</span></div><div className="guest"><p><b>@marina.exe</b> “Silent Hill 2 in the pantheon = respect.”</p><p><b>@caio</b> “absurd profile, as always 🔥”</p><button className="button ghost">SIGN GUESTBOOK</button></div></section>}<section className="profile-module"><div className="module-head"><Eyebrow>RECENT REVIEW</Eyebrow><h2>THE LAST LOG</h2><span>17 AUG</span></div><div className="review-mini"><Poster item={media[5]}/><div><h3>Cure</h3><Stars/><p>“The silence is the scariest part. Nothing here releases its grip.”</p></div></div></section></div>
  </div></div>{!ready&&<span className="profile-loading">LOADING PROFILE...</span>}</div>
}
