import Link from "next/link";
import { ArrowRight, Play, Sparkles } from "lucide-react";
import { featured, media } from "@/lib/data";
import { MediaCard, Poster } from "@/components/media-card";
import { Eyebrow, SectionHead, Stars } from "@/components/ui";

export default function Home(){return <>
 <section className="hero"><div className="hero-grid"><div className="hero-copy"><Eyebrow>THE CULTURAL IDENTITY NETWORK</Eyebrow><h1>EVERYTHING<br/>YOU <em>LOVE</em><br/>LEAVES A TRACE.</h1><p>Movies, games, books, football, and every obsession in between. Build an archive that feels unmistakably yours.</p><div className="hero-actions"><Link className="button primary" href="/lucas">ENTER THE ARCHIVE <ArrowRight size={17}/></Link><Link className="button ghost" href="/explore"><Play size={15}/> EXPLORE CULTURE</Link></div><div className="signal"><span/><b>12,804</b> cultural signals logged today</div></div><div className="hero-stack"><div className="orbit-label">A LIVING ARCHIVE</div>{featured.slice(0,3).map((x,i)=><div className={`stack-card s${i}`} key={x.id}><Poster item={x} large/><small>{x.type} / {x.year}</small></div>)}<div className="stamp">ARCHIVE<br/><b>WHAT MAKES</b><br/>YOU, YOU</div></div></div></section>
 <section className="ticker"><span>RECENT SIGNALS</span><div>● LUCAS FINISHED SILENT HILL 2 &nbsp; ✦ &nbsp; MARIA FAVORITED POSSESSION &nbsp; ✦ &nbsp; JOÃO CREATED “RAINY NIGHT CINEMA”</div></section>
 <section className="section"><SectionHead label="TRENDING NOW" title="The culture is moving." href="/explore"/><div className="media-grid">{media.slice(0,5).map(x=><MediaCard item={x} key={x.id}/>)}</div></section>
 <section className="section split"><div><SectionHead label="FROM THE COMMUNITY" title="Fresh from the feed." href="/feed"/><div className="activity"><div className="activity-user"><span className="avatar coral">M</span><p><b>marina.exe</b><small>LOGGED A FILM · 12 MIN AGO</small></p><span>•••</span></div><div className="activity-body"><Poster item={media[5]}/><div><span className="type type-film">● CINEMA</span><h3>Cure <small>(1997)</small></h3><Stars/><p>“It feels like the film is staring back at you. The silence is the scariest part.”</p><div className="reactions"><span>🔥 34</span><span>👁 12</span><span>🤝 8</span></div></div></div></div></div><div className="list-feature"><Eyebrow>POPULAR HYBRID LIST</Eyebrow><h2>Things that<br/><em>rewired my brain</em></h2><p>by @caio · 18 entries</p><div className="mini-stack">{media.slice(1,5).map(x=><Poster key={x.id} item={x}/>)}</div><Link href="/lists">OPEN LIST <ArrowRight size={16}/></Link></div></section>
 <section className="manifesto"><Sparkles/><p>Your profile shouldn't look like everyone else's.</p><h2>THE INTERNET WAS MORE<br/>INTERESTING WHEN PAGES<br/><em>BELONGED TO PEOPLE.</em></h2><Link href="/lucas" className="button primary">SEE A LIVING PROFILE <ArrowRight size={17}/></Link></section>
 </>}
